import type { NextPage } from "next";
import Head from "next/head";
//import Image from "next/image";
import styles from "../styles/Home.module.css";
import React from "react";
import Card from "../components/Card";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Card
          color={"hsl(31, 77%, 52%)"}
          url={"images/icon-sedans.svg"}
          title={"SEDANS"}
          text={
            "Choose a sedan for its affordability and excellent fuel economy. Ideal for cruising in the city or on your next road trip."
          }
        />
        <Card
          color={"hsl(184, 100%, 22%)"}
          url={"images/icon-suvs.svg"}
          title={"SUVS"}
          text={
            "Take an SUV for its spacious interior, power, and versatility. Perfect for your next family vacation and off-road adventures."
          }
        />
        <Card
          color={"hsl(179, 100%, 13%)"}
          url={"images/icon-luxury.svg"}
          title={"LUXURY"}
          text={
            "Cruise in the best car brands without the bloated prices. Enjoy the enhanced comfort of a luxury rental and arrive in style. "
          }
        />
      </main>
    </div>
  );
};

export default Home;
